apiVersion: v1
kind: Pod
metadata:
  name: node1
spec:
  containers:
    - name: master
      image: abhi2404/ansible-cluster
      ports:
        - containerPort: 22
      securityContext:
        privileged: true
